import { z } from "zod";

const envSchema = z.object({
  NODE_ENV: z.enum(["production", "development", "test"]).default("development"),
  PORT: z.coerce.number().default(3000),
  DATABASE_URL: z.url().startsWith("postgresql://"),
  ALLOWED_ORIGIN: z.url(),
  BETTER_AUTH_URL: z.url(),
  GOOGLE_CLIENT_ID: z.string(),
  GOOGLE_CLIENT_SECRET: z.string(),
  GOOGLE_REDIRECT_URI: z.url(),
  GOOGLE_REDIRECT_CALLBACK_URI: z.url(),
  R2_ENDPOINT: z.url(),
  R2_ACCESS_KEY_ID: z.string(),
  R2_SECRET_ACCESS_KEY: z.string(),
  R2_BUCKET_NAME: z.string(),
  REPLICATE_API_TOKEN: z.string(),
  GEMINI_API_KEY: z.string(),
  TRIGGER_SECRET_KEY: z.string(),
  MODAL_URL: z.url(),
  MODAL_TRANSCRIBE_AUDIO_URL: z.url(),
  TIKTOK_CLIENT_KEY: z.string(),
  TIKTOK_CLIENT_SECRET: z.string(),
  TIKTOK_REDIRECT_URI: z.url(),
  RESEND_API_KEY: z.string(),
  TIKTOK_REDIRECT_CALLBACK_URI: z.url(),
  QSTASH_URL: z.url(),
  QSTASH_TOKEN: z.string(),
  QSTASH_CURRENT_SIGNING_KEY: z.string(),
  QSTASH_NEXT_SIGNING_KEY: z.string(),
  QSTASH_TOPIC_URL: z.url(),
  AES_ENCRYPTION_KEY: z.string(),
  INSTAGRAM_APP_ID: z.string(),
  INSTAGRAM_APP_SECRET: z.string(),
  INSTAGRAM_ACCESS_TOKEN: z.string(),
  INSTAGRAM_REDIRECT_URI: z.url(),
  INSTAGRAM_REDIRECT_CALLBACK_URI: z.url(),
});

export const env = envSchema.parse(process.env);
