name: Deploy Storybook

on:
  pull_request:
    branches: [development]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Chromatic precisa do histórico completo pra fazer o diff com o baseline

      - run: npm install -g pnpm

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "pnpm"
          cache-dependency-path: web/pnpm-lock.yaml

      - name: Install web dependencies
        working-directory: web
        run: pnpm install --frozen-lockfile

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: web
        env:
          VITE_API_BASE_URL: http://localhost:3000
          VITE_NODE_ENV: test
